
<form id="form1" name="form1" method="post" action="<@ofbizUrl>saveAndMailTest</@ofbizUrl>">

   <table cellspacing="4"> 
	      <tr class="header-row">	      
			 <td colspan="3"><div align="center"><h1>E-mail Preferences</h1></div></td>	
	      </tr>  
	       
   <tr><td><b>Mail Server Domain Name: </b></td>
	   <td><input type="text" name="mailServer" value=${result.mailServer}  size="35"/></td>
	   <td><span class="tooltip">Enter the domain name of the mail server to use for sending SiteScope messages and alerts. This server should be an SMTP mail server. For example, gateway.this-company.com.</span>
	   </td>
   </tr>

   <tr><td><b>Administrator E-mail Address:</b> </td>
	   <td><input type="text" name="autoEmail" value=${result.autoEmail}  size="35"/></td>
	   <td><span class="tooltip">Enter the administrator e-mail address where SiteScope will send status messages. For example, support@mercury.com.</span>
	   </td>
   </tr>
    <tr><td><b>SiteScope Status Messages</b> </td>
    		
	  	<td><#if result.autoDaily?has_content&&result.autoDaily=="checked">	
				 <input type="checkbox" name="autoDaily" value="Y" checked="checked" />
			<#else>
				<input type="checkbox" name="autoDaily" value="Y"  />
			</#if>
	  		<br />
	       <#if result.autoStartup?has_content&&result.autoStartup=="checked">	
				 <input type="checkbox" name="autoStartup" value="Y" checked="checked" />
			<#else>
				<input type="checkbox" name="autoStartup" value="Y"  />
			</#if>
	       <br />
       </td>
   <td><span class="tooltip">Select which regularSiteScope status messages you would like to receive</span>
   </td>
   </tr>
    <tr><td><b>From Email Address:</b> </td>
	   <td><input type="text" name="fromAddress" value=${result.fromAddress}  size="35"/></td>
	   <td><span class="tooltip">(optional) Enter the email address used as the From Address for SiteScope messages. This is used to make it easier to browse or sort email generated by SiteScope. For example, support@mercury.com.</span>
	   </td>
   </tr>
   <tr><td><b>Backup Mail Server Domain Name:</b> </td>
	   <td><input type="text" name="mailServerBackup" value=${result.mailServerBackup}  size="35"/></td>
	   <td><span class="tooltip">(optional) Enter the domain name of a backup mail server to use for sending messages when the primary mail server cannot be reached. This server should be an SMTP mail server. For example,mail.this-company.com</span>
	   </td>
   </tr>   
  </table> 
  <p>
    <label>
    <input type="submit" name="" id="" value="${uiLabelMap.saveAndTest}" />
    </label>
  </p>
</form>